apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: xyzhao0201/bestbuy-order-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          env:
            - name: APP_ENV
              valueFrom:
                secretKeyRef:
                  name: bestbuy-secret
                  key: APP_ENV
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
    - port: 3002
      targetPort: 3002