apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: xyzhao0201/bestbuy-product-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: MONGO_URL
            - name: APP_ENV
              valueFrom:
                secretKeyRef:
                  name: bestbuy-secret
                  key: APP_ENV
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: ClusterIP
  selector:
    app: product-service
  ports:
    - port: 3001
      targetPort: 3001