apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-admin
  template:
    metadata:
      labels:
        app: store-admin
    spec:
      containers:
        - name: store-admin
          image: xyzhao0201/bestbuy-store-admin:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3004
          env:
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: PRODUCT_SERVICE_URL
            - name: ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: ORDER_SERVICE_URL
            - name: APP_ENV
              valueFrom:
                secretKeyRef:
                  name: bestbuy-secret
                  key: APP_ENV
---
apiVersion: v1
kind: Service
metadata:
  name: store-admin
spec:
  type: LoadBalancer
  selector:
    app: store-admin
  ports:
    - port: 80
      targetPort: 3004